### ISSUE TITLE
wokwi-potentiometers

### ISSUE THREAD

**Issue by jimf99** [wokwi/wokwi-elements#71]
Dial Potentiometers Series / Parallel Issues
===============================
I was using the Dial Potentiometer and noticed
that the VCC and GND had no real effect.
I tried connecting potentiometers in series
and parallel, and the values were still within range of 0-1023
Only 1 value range was output. 0-1023 from the SIG
pin.
https://github.com/wokwi/wokwi-elements/blob/master/src/potentiometer-element.ts

**Comment by urish** [comment]
Hi Jim!

Thanks for the feedback. That's because we don't have a true analog simulation, only digital simulation. 

The potentiometer is a special case: the output is fed directly into the ADC pin of the microchip, regardless of the VCC/GND connections. This is also mentioned in [the docs](https://docs.wokwi.com/parts/wokwi-potentiometer#pin-names) - see the "Note" under Pin Names. Perhaps we should make this more prominent ?

**Comment by jimf99** [comment]
Okay. Understood. I just jumped right in and started experimenting with the Potentiometers and "expected" certain predictable results, thanks for clarifying this.
Kind Regards from Calgary Alberta Canada.
